# Generated by Django 5.1.1 on 2024-09-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('type_medicament', models.CharField(max_length=100, verbose_name='Тип')),
                ('category_medicament', models.TextField(verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Принадлежит')),
            ],
        ),
    ]
