version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: medicaments
      POSTGRES_PASSWORD: medicaments
      POSTGRES_DB: medicaments
    volumes:
      - postgres_data:/usr/local/pgsql/data
    ports:
      - "5432:5432"
    networks:
      - medicaments

  medicaments:
    build: .
    container_name: medicaments
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - static_volume:/usr/scr/app/static
      - static_media:/usr/scr/app/media
    networks:
      - medicaments

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - static_media:/media
    ports:
      - "8080:80"
    depends_on:
      - medicaments
    networks:
      - medicaments

volumes:
  static_volume:
  static_media:
  postgres_data:

networks:
  medicaments:
    driver: bridge
